### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by jehiah** [stripe/sequins#105]
There have been quite a few commits since the last release (almost a year ago). 

Is there any interest in stamping a new release? 

cheers.

**Comment by scottjab-stripe** [comment]
Hello! We're currently at work on a couple of features related to data ingestion and balancing, which we think are important to ensure Sequins' stability at a larger scale. We'll likely cut a release when those are done—ETA is about a month.  

Do you use sequins? If so, we would love any feedback on the type of workloads you use it for.

**Comment by jehiah** [comment]
@scottjab-stripe No, I don't use sequins at the moment, but architecturally i like it's approach very much so i'm interested in it for a few potential uses. 

I do heavily use [sortdb](https://github.com/jehiah/sortdb) which provides a very similar HTTP api to static sorted datasets (probably notably different in providing range/prefix queries). I have long wanted to build something on top of sortdb to solve higher order distributed/replicated needs. It seems feasible that i might be able to accomplish that with `sequins` and support for a sortdb data format.

(I also don't use zookeeper but presumably I could cross that bridge with something like [coreos/zetcd](https://github.com/coreos/zetcd))

**Comment by scottjab-stripe** [comment]
We have some ideas to support range queries in the future, we will probably have to change the underlying storage engine that sequins uses though. 

Regarding zookeeper I don't see us dropping that dependency anytime soon, if we do we will probably use something like [hashicorp/consul](https://github.com/hashicorp/consul)

Most of the work we have been doing over the last few months have been to increase sequins reliability when deployed in a large cluster.

**Comment by jehiah** [comment]
👍  Thanks for the insight into status of things here. ❤️  consul. cockroachdb might also be a good choice for a backing store.

For some concrete use case details; One use I have is a 20T dataset that currently gets rebuilt and delivered to 96 `sortdb` daily. If that process were easier I'd use it for other workloads as well =)

**Comment by jehiah** [comment]
p.s. as you answered my original question, feel free to close this!

**Comment by scottjab-stripe** [comment]
Interesting, we have been investigating just having hadoop generate the on disk format [sparkey](https://github.com/spotify/sparkey) for sequins, instead of using sequence files as an intermediary step.  We have seen rather large gains in dataset loading performance by doing this. 

Thanks for the use case info, that is super interesting.
