### ISSUE TITLE
Serve data from existing indexes upon startup

### ISSUE THREAD

**Issue by franklinhu** [stripe/sequins#14]
When Sequins starts up, it does not serve data from the existing leveldb indexes if newer data sets exist. This is an issue if the service is restarted, since blocking on indexing can take quite some time.

Ideally, Sequins would start up serving any existing indexes, then swap in the newer data as it comes available.

**Comment by colinmarc** [comment]
Hi Franklin,

If a manifest file exists, it should only CRC the file and not reindex
entirely. Are you seeing different behavior?

(CRCing still takes a while on large datasets, so we may want to do away
with that too.)
