### ISSUE TITLE
sequencefile: keylength isn't properly checked

### ISSUE THREAD

**Issue by jordanorelli** [stripe/sequins#2]
in certain failure situations, a sequence file can fail to parse in strange ways that create records that report that they have negative key lengths.  When reading a sequence file, it's checked that the total key length cannot be less than 0, but then 4 is taken from that; keyLengths can thus be -1 to -3.

https://github.com/stripe/sequins/blob/b5e7a386814ffe1bb88a0092d7d57119a841b5f6/sequencefile/sequencefile.go#L243-L248

this part:
```go
	if totalKeyLength < 0 {
		return nil, fmt.Errorf("Invalid key length: %d", totalKeyLength)
	}

	keyOffset := sf.offset + 4 // skip four for BytesWritable length
	keyLength := int64(totalKeyLength) - 4
```

should be:

```go
	keyOffset := sf.offset + 4 // skip four for BytesWritable length
	keyLength := int64(totalKeyLength) - 4

	if keyLength < 0 {
		return nil, fmt.Errorf("Invalid key length: %d", keyLength)
	}
```

unless, of course, negative key lengths are sometimes valid.

**Comment by colinmarc** [comment]
I fixed this when I rewrote the sequencefile code in #4. Thanks for the report!
